### ISSUE TITLE
Feature request - push notification

### ISSUE THREAD

**Issue by rubens21** [brenu/spotify-lyrics#1]
A pagina nao se atualiza quando eu troco de musica ou quando eu comeco a ouvir uma musica.

O servico poderia verificar se eu pulei a musca ou dei play, e ai atualizar a pagina sozinha

**Comment by brenu** [comment]
O serviço agora faz novas verificações à partir de um dado intervalo de tempo. Logo, para cada alteração que ocorra no Spotify, a página pode vir a ser atualizada por conta própria.
