### ISSUE TITLE
Bug quando tenta re-carregar a pagina

### ISSUE THREAD

**Issue by rubens21** [brenu/spotify-lyrics#2]
Quando eu tento recarregar a pagina pra atualizar a musica que eu to ouvindo, a pagina quebra:

![image](https://user-images.githubusercontent.com/447656/89457351-3c1c1a00-d733-11ea-8d9f-8e97c34a1b5a.png)

**Comment by brenu** [comment]
Resolvido. Esse problema não acontecerá mais :)
