### ISSUE TITLE
A letra da musica ficam quebradas pq nao tem espaco pra frase inteira

### ISSUE THREAD

**Issue by rubens21** [brenu/spotify-lyrics#3]
![image](https://user-images.githubusercontent.com/447656/89457628-aa60dc80-d733-11ea-96b3-38c51d899772.png)

**Comment by brenu** [comment]
O container com a letra da música tava limitado a uma largura de 600px mesmo pra telas maiores, meu mal. Coloquei um limite maior para telas maiores.
