### ISSUE TITLE
Add player please

### ISSUE THREAD

**Issue by FiftyFour7250** [brenu/spotify-lyrics#7]
Hey. I really like your app. But I beg you to add a player, with the ability to rewind, by clicking on the playback bar (as it works in any player). Just, you know, it's a little inconvenient when I listening a song with lyrics, want to rewind, and I have to open Spotify and then go back....
If you agree to add this, it would be cool if the player bar was pinned, that when you read the last verse, and you wanted to pause - didn't have to scroll to the top. Hope you know what I mean)

**Comment by brenu** [comment]
I believe I can do that, and also have to apologize for the time I took to answer this issue. There's this college stuff and work and blah blah blah.

Anyway, I'll keep you updated, thank you for the suggestion :)

**Comment by brenu** [comment]
From now on, you're able to play/pause and skip tracks. I'll be implementing rewind and fastforward options by tomorrow.

**Comment by FiftyFour7250** [comment]
Ok, thanks)

**Comment by brenu** [comment]
Changes done :D

Tell me whether it's working as you were expecting or not

**Comment by FiftyFour7250** [comment]
Not quite. I thought there would be a playback bar (line), and on click there would be a rewind. 

![Снимок](https://user-images.githubusercontent.com/78786088/112678612-2ef79b00-8e7c-11eb-95ff-1e7cfd383b1e.JPG)

Just, you know, buttons for rewind to 5 seconds - cool, but if I read the lyrics, and want to rewind even for at least 30 seconds - I still have to open Spotify and then go back... Little inconvenient. I think 5 second buttons could be on keyboard arrows, like on YouTube.

**Comment by brenu** [comment]
Playback bar implemented too. I didn't see the "bar" part when you first requested it, my bad.

**Comment by FiftyFour7250** [comment]
Yea, it works great now, real thank you. Although I think that it would be possible to make this panel a little longer

![123213](https://user-images.githubusercontent.com/78786088/112767206-04454800-901e-11eb-96ff-73d7fc40386e.JPG)

But even now it's fine, thanks.

**Comment by brenu** [comment]
I'll remember to make it longer when I'll be migrating the project to a different domain. It definitely looks tiny from your screen's perspective.
